//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreDiabetes.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PreDiabetes.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anos).
        /// </summary>
        public static string AgeCaption {
            get {
                return ResourceManager.GetString("AgeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Idade inválida).
        /// </summary>
        public static string AgeCaptionInvalid {
            get {
                return ResourceManager.GetString("AgeCaptionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data do backup: .
        /// </summary>
        public static string Backup_DateLabel {
            get {
                return ResourceManager.GetString("Backup_DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum backup efetuado até agora..
        /// </summary>
        public static string Backup_NoBackup {
            get {
                return ResourceManager.GetString("Backup_NoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho: .
        /// </summary>
        public static string Backup_PathLabel {
            get {
                return ResourceManager.GetString("Backup_PathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup criado em: {0}.
        /// </summary>
        public static string BackupCreatedMessageFormat {
            get {
                return ResourceManager.GetString("BackupCreatedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente cria um backup da base de dados?.
        /// </summary>
        public static string ConfirmBackupMessage {
            get {
                return ResourceManager.GetString("ConfirmBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Backup.
        /// </summary>
        public static string ConfirmBackupTitle {
            get {
                return ResourceManager.GetString("ConfirmBackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A operação irá substituir a base de dados atual pelo backup. Deseja continuar?.
        /// </summary>
        public static string ConfirmRestoreMessage {
            get {
                return ResourceManager.GetString("ConfirmRestoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação inválida / Dados inválidos ou em falta.
        /// </summary>
        public static string DadosEmFalta {
            get {
                return ResourceManager.GetString("DadosEmFalta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar.
        /// </summary>
        public static string DeleteMsg {
            get {
                return ResourceManager.GetString("DeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O seu dispositivo não é compatível..
        /// </summary>
        public static string DeviceNotSupported {
            get {
                return ResourceManager.GetString("DeviceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string EditMsg {
            get {
                return ResourceManager.GetString("EditMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização não disponível.
        /// </summary>
        public static string ErroLocalizacaoNaoDisponivel {
            get {
                return ResourceManager.GetString("ErroLocalizacaoNaoDisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning errors occurred while counting some tables (marked as ERR). Check the logs..
        /// </summary>
        public static string ErrorCountingTablesHint {
            get {
                return ResourceManager.GetString("ErrorCountingTablesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravar.
        /// </summary>
        public static string Gravar {
            get {
                return ResourceManager.GetString("Gravar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Várias tabelas ateradas.
        /// </summary>
        public static string MultipleTablesChangedHeader {
            get {
                return ResourceManager.GetString("MultipleTablesChangedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Nao {
            get {
                return ResourceManager.GetString("Nao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string NewMsg {
            get {
                return ResourceManager.GetString("NewMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe qualquer backup para restaurar.
        /// </summary>
        public static string NoBackupMessage {
            get {
                return ResourceManager.GetString("NoBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem backup.
        /// </summary>
        public static string NoBackupTitle {
            get {
                return ResourceManager.GetString("NoBackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O backup tem o mesmo número de registos em todas as tabelas. Não há necessidade de restaurar..
        /// </summary>
        public static string NoChangesMessage {
            get {
                return ResourceManager.GetString("NoChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem alterações.
        /// </summary>
        public static string NoChangesTitle {
            get {
                return ResourceManager.GetString("NoChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma tabela foi alterada.
        /// </summary>
        public static string NoTableChanged {
            get {
                return ResourceManager.GetString("NoTableChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi detetada 1 tabela alterada.
        /// </summary>
        public static string OneTableChangedFormat {
            get {
                return ResourceManager.GetString("OneTableChangedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi detetada 1 tabela alterada.
        /// </summary>
        public static string OneTableChangedHeader {
            get {
                return ResourceManager.GetString("OneTableChangedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Pet_Brand {
            get {
                return ResourceManager.GetString("Pet_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raça.
        /// </summary>
        public static string Pet_Breed {
            get {
                return ResourceManager.GetString("Pet_Breed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultas.
        /// </summary>
        public static string Pet_Consultations {
            get {
                return ResourceManager.GetString("Pet_Consultations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desparasitantes.
        /// </summary>
        public static string Pet_Dewormers {
            get {
                return ResourceManager.GetString("Pet_Dewormers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ração.
        /// </summary>
        public static string Pet_Food {
            get {
                return ResourceManager.GetString("Pet_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho.
        /// </summary>
        public static string Pet_Size {
            get {
                return ResourceManager.GetString("Pet_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esterilizado.
        /// </summary>
        public static string Pet_Sterilised {
            get {
                return ResourceManager.GetString("Pet_Sterilised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets.
        /// </summary>
        public static string Pet_Title {
            get {
                return ResourceManager.GetString("Pet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string Pet_Vaccine_Brand {
            get {
                return ResourceManager.GetString("Pet_Vaccine_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toma.
        /// </summary>
        public static string Pet_Vaccine_Date {
            get {
                return ResourceManager.GetString("Pet_Vaccine_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacina.
        /// </summary>
        public static string Pet_Vaccine_Name {
            get {
                return ResourceManager.GetString("Pet_Vaccine_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próxima.
        /// </summary>
        public static string Pet_Vaccine_Next {
            get {
                return ResourceManager.GetString("Pet_Vaccine_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próxima toma.
        /// </summary>
        public static string Pet_Vaccine_Next_Dose {
            get {
                return ResourceManager.GetString("Pet_Vaccine_Next_Dose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacinas.
        /// </summary>
        public static string Pet_Vaccines {
            get {
                return ResourceManager.GetString("Pet_Vaccines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo anulado com sucesso.
        /// </summary>
        public static string RegistoAnuladoSucesso {
            get {
                return ResourceManager.GetString("RegistoAnuladoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo inserido com sucesso.
        /// </summary>
        public static string RegistoCriadoSucesso {
            get {
                return ResourceManager.GetString("RegistoCriadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo atualizado com sucesso.
        /// </summary>
        public static string RegistoGravadoSucesso {
            get {
                return ResourceManager.GetString("RegistoGravadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base de dados atual.
        /// </summary>
        public static string Restore_BD_Atual {
            get {
                return ResourceManager.GetString("Restore_BD_Atual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup selecionado.
        /// </summary>
        public static string Restore_BD_Selecionada {
            get {
                return ResourceManager.GetString("Restore_BD_Selecionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Restore.
        /// </summary>
        public static string Restore_Botao_Confirmacao {
            get {
                return ResourceManager.GetString("Restore_Botao_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registos.
        /// </summary>
        public static string Restore_Registos {
            get {
                return ResourceManager.GetString("Restore_Registos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registos alterados.
        /// </summary>
        public static string Restore_Registos_Alterados {
            get {
                return ResourceManager.GetString("Restore_Registos_Alterados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelas.
        /// </summary>
        public static string Restore_Tabelas {
            get {
                return ResourceManager.GetString("Restore_Tabelas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base de dados restaurada com sucesso!.
        /// </summary>
        public static string RestoreSuccessMessage {
            get {
                return ResourceManager.GetString("RestoreSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Restore.
        /// </summary>
        public static string RestoreSuccessTitle {
            get {
                return ResourceManager.GetString("RestoreSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string Sair {
            get {
                return ResourceManager.GetString("Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Sim {
            get {
                return ResourceManager.GetString("Sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo foi eliminado com sucesso..
        /// </summary>
        public static string SuccessDelete {
            get {
                return ResourceManager.GetString("SuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo foi criado com sucesso..
        /// </summary>
        public static string SuccessInsert {
            get {
                return ResourceManager.GetString("SuccessInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo foi gravado com sucesso..
        /// </summary>
        public static string SuccessUpdate {
            get {
                return ResourceManager.GetString("SuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo(s) atualizado(s) com sucesso..
        /// </summary>
        public static string SuccessUpdates {
            get {
                return ResourceManager.GetString("SuccessUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver no mapa.
        /// </summary>
        public static string TipoVerNoMapa {
            get {
                return ResourceManager.GetString("TipoVerNoMapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string Titulo_De {
            get {
                return ResourceManager.GetString("Titulo_De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um dos Pets abaixo, para visualizar os dados.
        /// </summary>
        public static string Titulo_Main_Info {
            get {
                return ResourceManager.GetString("Titulo_Main_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há Pets para tratar....
        /// </summary>
        public static string Titulo_NoPets {
            get {
                return ResourceManager.GetString("Titulo_NoPets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string Titulo_Titulo {
            get {
                return ResourceManager.GetString("Titulo_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar.
        /// </summary>
        public static string TituloAplicarIdioma {
            get {
                return ResourceManager.GetString("TituloAplicarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem da App Maui Pets / Logs.
        /// </summary>
        public static string TituloAssuntoEMail {
            get {
                return ResourceManager.GetString("TituloAssuntoEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup da base de dados.
        /// </summary>
        public static string TituloBackup {
            get {
                return ResourceManager.GetString("TituloBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string TituloCategoria {
            get {
                return ResourceManager.GetString("TituloCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chipado.
        /// </summary>
        public static string TituloChipado {
            get {
                return ResourceManager.GetString("TituloChipado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do chip.
        /// </summary>
        public static string TituloCodigoChip {
            get {
                return ResourceManager.GetString("TituloCodigoChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra.
        /// </summary>
        public static string TituloCompra {
            get {
                return ResourceManager.GetString("TituloCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações principais.
        /// </summary>
        public static string TituloConfiracoesPrincipais {
            get {
                return ResourceManager.GetString("TituloConfiracoesPrincipais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme, por favor.
        /// </summary>
        public static string TituloConfirmacao {
            get {
                return ResourceManager.GetString("TituloConfirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apaga o registo?.
        /// </summary>
        public static string TituloConfirmacao_Apagar {
            get {
                return ResourceManager.GetString("TituloConfirmacao_Apagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultas no veterinário.
        /// </summary>
        public static string TituloConsultasVeterinario {
            get {
                return ResourceManager.GetString("TituloConsultasVeterinario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactos.
        /// </summary>
        public static string TituloContactos {
            get {
                return ResourceManager.GetString("TituloContactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cor.
        /// </summary>
        public static string TituloCor {
            get {
                return ResourceManager.GetString("TituloCor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados Biográficos.
        /// </summary>
        public static string TituloDadosBiograficos {
            get {
                return ResourceManager.GetString("TituloDadosBiograficos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da colocação.
        /// </summary>
        public static string TituloDataChip {
            get {
                return ResourceManager.GetString("TituloDataChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fim.
        /// </summary>
        public static string TituloDataFim {
            get {
                return ResourceManager.GetString("TituloDataFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data no futuro.
        /// </summary>
        public static string TituloDataFuturo {
            get {
                return ResourceManager.GetString("TituloDataFuturo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data início.
        /// </summary>
        public static string TituloDataInicio {
            get {
                return ResourceManager.GetString("TituloDataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja descartar esta notiicação.
        /// </summary>
        public static string TituloDescartarNotificacao {
            get {
                return ResourceManager.GetString("TituloDescartarNotificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string TituloDescricao {
            get {
                return ResourceManager.GetString("TituloDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição (opcional).
        /// </summary>
        public static string TituloDescricaoOpcional {
            get {
                return ResourceManager.GetString("TituloDescricaoOpcional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despesa.
        /// </summary>
        public static string TituloDespesa {
            get {
                return ResourceManager.GetString("TituloDespesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despesas.
        /// </summary>
        public static string TituloDespesas {
            get {
                return ResourceManager.GetString("TituloDespesas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despesas agrupadas.
        /// </summary>
        public static string TituloDespesasAgrupadas {
            get {
                return ResourceManager.GetString("TituloDespesasAgrupadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despesas por Categoria.
        /// </summary>
        public static string TituloDespesasPorCategoria {
            get {
                return ResourceManager.GetString("TituloDespesasPorCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas as despesas.
        /// </summary>
        public static string TituloDespesasTodasDespesas {
            get {
                return ResourceManager.GetString("TituloDespesasTodasDespesas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos.
        /// </summary>
        public static string TituloDocumentos {
            get {
                return ResourceManager.GetString("TituloDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doenças.
        /// </summary>
        public static string TituloDoencas {
            get {
                return ResourceManager.GetString("TituloDoencas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doenças Crónicas.
        /// </summary>
        public static string TituloDoencasCronicas {
            get {
                return ResourceManager.GetString("TituloDoencasCronicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dt. Nascº.
        /// </summary>
        public static string TituloDtNascimento {
            get {
                return ResourceManager.GetString("TituloDtNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duração.
        /// </summary>
        public static string TituloDuracao {
            get {
                return ResourceManager.GetString("TituloDuracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string TituloEmail {
            get {
                return ResourceManager.GetString("TituloEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preenha os campos requeridos, p.f..
        /// </summary>
        public static string TituloEntradasEmFalta {
            get {
                return ResourceManager.GetString("TituloEntradasEmFalta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao apagar registo.
        /// </summary>
        public static string TituloErroDelete {
            get {
                return ResourceManager.GetString("TituloErroDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao criar registo.
        /// </summary>
        public static string TituloErroInsert {
            get {
                return ResourceManager.GetString("TituloErroInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na partilha de Pdf.
        /// </summary>
        public static string TituloErroPartilha {
            get {
                return ResourceManager.GetString("TituloErroPartilha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na atualização.
        /// </summary>
        public static string TituloErroUpdate {
            get {
                return ResourceManager.GetString("TituloErroUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erros na validação.
        /// </summary>
        public static string TituloErroValidacao {
            get {
                return ResourceManager.GetString("TituloErroValidacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione categoria.
        /// </summary>
        public static string TituloEscolhaCategoria {
            get {
                return ResourceManager.GetString("TituloEscolhaCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha espécie.
        /// </summary>
        public static string TituloEscolhaEspecie {
            get {
                return ResourceManager.GetString("TituloEscolhaEspecie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha foto.
        /// </summary>
        public static string TituloEscolhaImagem {
            get {
                return ResourceManager.GetString("TituloEscolhaImagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha o Pet.
        /// </summary>
        public static string TituloEscolhaPet {
            get {
                return ResourceManager.GetString("TituloEscolhaPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha raça.
        /// </summary>
        public static string TituloEscolhaRaca {
            get {
                return ResourceManager.GetString("TituloEscolhaRaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha situacao.
        /// </summary>
        public static string TituloEscolhaSituacao {
            get {
                return ResourceManager.GetString("TituloEscolhaSituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha tamanho.
        /// </summary>
        public static string TituloEscolhaTamanho {
            get {
                return ResourceManager.GetString("TituloEscolhaTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha temperamento.
        /// </summary>
        public static string TituloEscolhaTemperamento {
            get {
                return ResourceManager.GetString("TituloEscolhaTemperamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione tipo.
        /// </summary>
        public static string TituloEscolhaTipo {
            get {
                return ResourceManager.GetString("TituloEscolhaTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espécie.
        /// </summary>
        public static string TituloEspecie {
            get {
                return ResourceManager.GetString("TituloEspecie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string TituloEstado {
            get {
                return ResourceManager.GetString("TituloEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta semana.
        /// </summary>
        public static string TituloEstaSemana {
            get {
                return ResourceManager.GetString("TituloEstaSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este ano.
        /// </summary>
        public static string TituloEsteAno {
            get {
                return ResourceManager.GetString("TituloEsteAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este mês.
        /// </summary>
        public static string TituloEsteMes {
            get {
                return ResourceManager.GetString("TituloEsteMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar para Pdf.
        /// </summary>
        public static string TituloExportarPdf {
            get {
                return ResourceManager.GetString("TituloExportarPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faixa etária.
        /// </summary>
        public static string TituloFaixaEtaria {
            get {
                return ResourceManager.GetString("TituloFaixaEtaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fèmea.
        /// </summary>
        public static string TituloFeminino {
            get {
                return ResourceManager.GetString("TituloFeminino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficha de.
        /// </summary>
        public static string TituloFichaDe {
            get {
                return ResourceManager.GetString("TituloFichaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficheiro temporário inexistenete. Por favor selecione novamente.
        /// </summary>
        public static string TituloFicheiroInexistente {
            get {
                return ResourceManager.GetString("TituloFicheiroInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim.
        /// </summary>
        public static string TituloFim {
            get {
                return ResourceManager.GetString("TituloFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string TituloFoto {
            get {
                return ResourceManager.GetString("TituloFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeria de fotos.
        /// </summary>
        public static string TituloGaleriaFotos {
            get {
                return ResourceManager.GetString("TituloGaleriaFotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelas.
        /// </summary>
        public static string TituloGestaoTabelas {
            get {
                return ResourceManager.GetString("TituloGestaoTabelas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idade.
        /// </summary>
        public static string TituloIdade {
            get {
                return ResourceManager.GetString("TituloIdade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string TituloIdioma {
            get {
                return ResourceManager.GetString("TituloIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        public static string TituloIdiomaIngles {
            get {
                return ResourceManager.GetString("TituloIdiomaIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        public static string TituloIdiomaPortugues {
            get {
                return ResourceManager.GetString("TituloIdiomaPortugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomas.
        /// </summary>
        public static string TituloIdiomas {
            get {
                return ResourceManager.GetString("TituloIdiomas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem.
        /// </summary>
        public static string TituloImagem {
            get {
                return ResourceManager.GetString("TituloImagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indique um título para o documento.
        /// </summary>
        public static string TituloIndiqueTitulo {
            get {
                return ResourceManager.GetString("TituloIndiqueTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação do último backup.
        /// </summary>
        public static string TituloInfoBackup {
            get {
                return ResourceManager.GetString("TituloInfoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        public static string TituloInicio {
            get {
                return ResourceManager.GetString("TituloInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A alteração aplica‑se imediatamente; reinicie a aplicação para garantir que todas as strings são atualizadas..
        /// </summary>
        public static string TituloLabelIdioma {
            get {
                return ResourceManager.GetString("TituloLabelIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidade.
        /// </summary>
        public static string TituloLocalidade {
            get {
                return ResourceManager.GetString("TituloLocalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string TituloMarca {
            get {
                return ResourceManager.GetString("TituloMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macho.
        /// </summary>
        public static string TituloMasculino {
            get {
                return ResourceManager.GetString("TituloMasculino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicação.
        /// </summary>
        public static string TituloMedicacao {
            get {
                return ResourceManager.GetString("TituloMedicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morada.
        /// </summary>
        public static string TituloMorada {
            get {
                return ResourceManager.GetString("TituloMorada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        public static string TituloMotivo {
            get {
                return ResourceManager.GetString("TituloMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemóvel.
        /// </summary>
        public static string TituloMovel {
            get {
                return ResourceManager.GetString("TituloMovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimento.
        /// </summary>
        public static string TituloMovimento {
            get {
                return ResourceManager.GetString("TituloMovimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string TituloNome {
            get {
                return ResourceManager.GetString("TituloNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observações.
        /// </summary>
        public static string TituloNotas {
            get {
                return ResourceManager.GetString("TituloNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros dados.
        /// </summary>
        public static string TituloOutrosDados {
            get {
                return ResourceManager.GetString("TituloOutrosDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padrinho.
        /// </summary>
        public static string TituloPadrinho {
            get {
                return ResourceManager.GetString("TituloPadrinho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagª.
        /// </summary>
        public static string TituloPagina_Abrev {
            get {
                return ResourceManager.GetString("TituloPagina_Abrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente.
        /// </summary>
        public static string TituloPendente {
            get {
                return ResourceManager.GetString("TituloPendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendentes.
        /// </summary>
        public static string TituloPendentes {
            get {
                return ResourceManager.GetString("TituloPendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso.
        /// </summary>
        public static string TituloPeso {
            get {
                return ResourceManager.GetString("TituloPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string TituloPesquisarContacto {
            get {
                return ResourceManager.GetString("TituloPesquisarContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prazo em meses.
        /// </summary>
        public static string TituloPrazoEmMeses {
            get {
                return ResourceManager.GetString("TituloPrazoEmMeses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próx. semana.
        /// </summary>
        public static string TituloProximaSemana {
            get {
                return ResourceManager.GetString("TituloProximaSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próx. mês.
        /// </summary>
        public static string TituloProxMes {
            get {
                return ResourceManager.GetString("TituloProxMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtd. diária.
        /// </summary>
        public static string TituloQtdDiaria {
            get {
                return ResourceManager.GetString("TituloQtdDiaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtd.
        /// </summary>
        public static string TituloQuantidadeAbr {
            get {
                return ResourceManager.GetString("TituloQuantidadeAbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação não permitida. Há registos associados. Verifique, por favor.
        /// </summary>
        public static string TituloRegistosAssociados {
            get {
                return ResourceManager.GetString("TituloRegistosAssociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurar base dados.
        /// </summary>
        public static string TituloRestore {
            get {
                return ResourceManager.GetString("TituloRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segurança.
        /// </summary>
        public static string TituloSeguranca {
            get {
                return ResourceManager.GetString("TituloSeguranca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione idioma.
        /// </summary>
        public static string TituloSelecionarIdioma {
            get {
                return ResourceManager.GetString("TituloSelecionarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione Pdf.
        /// </summary>
        public static string TituloSelecionarPdf {
            get {
                return ResourceManager.GetString("TituloSelecionarPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem dados para mostrar.
        /// </summary>
        public static string TituloSemDados {
            get {
                return ResourceManager.GetString("TituloSemDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração.
        /// </summary>
        public static string TituloSettings {
            get {
                return ResourceManager.GetString("TituloSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género.
        /// </summary>
        public static string TituloSexo {
            get {
                return ResourceManager.GetString("TituloSexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string TituloSituacao {
            get {
                return ResourceManager.GetString("TituloSituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa.
        /// </summary>
        public static string TituloTarefa {
            get {
                return ResourceManager.GetString("TituloTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluída.
        /// </summary>
        public static string TituloTarefa_Concluida {
            get {
                return ResourceManager.GetString("TituloTarefa_Concluida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefas.
        /// </summary>
        public static string TituloTarefas {
            get {
                return ResourceManager.GetString("TituloTarefas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefas concluídas.
        /// </summary>
        public static string TituloTarefas_Concluidas {
            get {
                return ResourceManager.GetString("TituloTarefas_Concluidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para esta semana.
        /// </summary>
        public static string TituloTarefas_EstaSemana {
            get {
                return ResourceManager.GetString("TituloTarefas_EstaSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para este mês.
        /// </summary>
        public static string TituloTarefas_EsteMes {
            get {
                return ResourceManager.GetString("TituloTarefas_EsteMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrado por.
        /// </summary>
        public static string TituloTarefas_Filtro {
            get {
                return ResourceManager.GetString("TituloTarefas_Filtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefas pendentes.
        /// </summary>
        public static string TituloTarefas_Pendentes {
            get {
                return ResourceManager.GetString("TituloTarefas_Pendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para a próxima semana.
        /// </summary>
        public static string TituloTarefas_ProximaSemana {
            get {
                return ResourceManager.GetString("TituloTarefas_ProximaSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para o próximo mês.
        /// </summary>
        public static string TituloTarefas_ProximoMes {
            get {
                return ResourceManager.GetString("TituloTarefas_ProximoMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas as tarefas.
        /// </summary>
        public static string TituloTarefas_Todas {
            get {
                return ResourceManager.GetString("TituloTarefas_Todas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperamento.
        /// </summary>
        public static string TituloTemperamento {
            get {
                return ResourceManager.GetString("TituloTemperamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string TituloTipo {
            get {
                return ResourceManager.GetString("TituloTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de contacto.
        /// </summary>
        public static string TituloTipoContacto {
            get {
                return ResourceManager.GetString("TituloTipoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas as consultas.
        /// </summary>
        public static string TituloTodasConsultas {
            get {
                return ResourceManager.GetString("TituloTodasConsultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas as vacinas.
        /// </summary>
        public static string TituloTodasVacinas {
            get {
                return ResourceManager.GetString("TituloTodasVacinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string TituloTodos {
            get {
                return ResourceManager.GetString("TituloTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string TituloValor {
            get {
                return ResourceManager.GetString("TituloValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique entradas, por favor.
        /// </summary>
        public static string TituloVerificarEntradas {
            get {
                return ResourceManager.GetString("TituloVerificarEntradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visita.
        /// </summary>
        public static string TituloVisita {
            get {
                return ResourceManager.GetString("TituloVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string TituloVoltar {
            get {
                return ResourceManager.GetString("TituloVoltar", resourceCulture);
            }
        }
    }
}
